name: flutter_pos_printer_platform_example
description: "Demonstrates how to use the flutter_pos_printer_platform plugin."
publish_to: "none"

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_pos_printer_platform:
    path: ../

  cupertino_icons: ^1.0.8
  dart_ping_ios: ^4.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family:
  #     fonts:
  #       - asset:
