name: flutter_pos_printer_platform
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.1.8
  hex: ^0.2.0
  gbk_codec: ^0.4.0
  rxdart: ^0.28.0
  dart_ping: ^9.0.1
  ping_discover_network_forked: ^0.0.1
  network_info_plus: ^6.0.0
  enum_to_string: ^2.0.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_pos_printer_platform
        pluginClass: FlutterPosPrinterPlatformPlugin
      ios:
        pluginClass: FlutterPosPrinterPlatformPlugin
      linux:
        pluginClass: FlutterPosPrinterPlatformPlugin
      macos:
        pluginClass: FlutterPosPrinterPlatformPlugin
      windows:
        pluginClass: FlutterPosPrinterPlatformPluginCApi
      web:
        pluginClass: FlutterPosPrinterPlatformWeb
        fileName: flutter_pos_printer_platform_web.dart

  assets:
    - assets/resources/capabilities.json
    - packages/flutter_pos_printer_platform/resources/capabilities.json

  # fonts:
  #   - family:
  #     fonts:
  #       - asset:
